import {db,auth,onAuthStateChanged,currentUserProfile,collection,collectionGroup,doc,getDoc,getDocs,setDoc,addDoc,updateDoc,deleteDoc,query,orderBy,limit,serverTimestamp} from "./firebase.js";
import {setupUI} from "./ui.js"; setupUI();
const $=s=>document.querySelector(s); let me,categories=[];
const esc=s=>(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));

// Journal d'activité affiché dans le tableau de bord
async function logActivity(action,label){
 try{ await addDoc(collection(db,"activity"),{action,label,byName:me?.displayName||me?.email||"?",createdAt:serverTimestamp()}); }catch(e){ console.error("Impossible d'enregistrer l'activité :",e); }
}
const ACTIVITY_ICONS={"artwork-add":"🎨","artwork-edit":"✏️","artwork-delete":"🗑️","category-add":"📁","category-delete":"📁","news-add":"📰"};
const ACTIVITY_LABELS={"artwork-add":"a ajouté le dessin","artwork-edit":"a modifié le dessin","artwork-delete":"a supprimé le dessin","category-add":"a ajouté la catégorie","category-delete":"a supprimé la catégorie","news-add":"a publié l'actualité"};
async function loadActivity(){
 const s=await getDocs(query(collection(db,"activity"),orderBy("createdAt","desc"),limit(15)));
 $("#recentActivity").innerHTML=s.docs.map(d=>{const a=d.data();const icon=ACTIVITY_ICONS[a.action]||"•";const verb=ACTIVITY_LABELS[a.action]||a.action;const date=a.createdAt?.toDate?.().toLocaleString?.("fr-FR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})||"";return `<div class="list-row"><span>${icon} <b>${esc(a.byName)}</b> ${esc(verb)} « ${esc(a.label)} »</span><small>${date}</small></div>`}).join("")||"<div class='empty'>Aucune activité récente.</div>";
}

onAuthStateChanged(auth,async user=>{
 if(!user){$("#adminDenied").classList.remove("hidden");return;}
 me=await currentUserProfile(user);
 if(!me||!["owner","admin","moderator"].includes(me.role)){$("#adminDenied").classList.remove("hidden");return;}
 $("#adminApp").classList.remove("hidden");$("#adminUser").textContent=`${me.displayName||user.email} · ${me.role}`; boot();
});
document.querySelectorAll(".admin-nav[data-section]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".admin-nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".admin-section").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.section).classList.add("active");$("#adminTitle").textContent=b.textContent.trim();});
async function boot(){await loadCategories();await loadArtworks();await loadUsers();await loadComments();await loadReports();await loadNews();await loadGoals();await loadSettings();await loadStats();await loadActivity();}

async function loadCategories(){const s=await getDocs(collection(db,"categories"));categories=s.docs.map(d=>({id:d.id,...d.data()}));$("#artCategory").innerHTML=categories.length?categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join(""):"";$("#adminCategories").innerHTML=categories.map(c=>`<div class="list-row"><span><b>${esc(c.name)}</b><small>${esc(c.description||"")}</small></span><button class="danger-btn" data-delcat="${c.id}">Supprimer</button></div>`).join("")||"<div class='empty'>Aucune catégorie. Ajoute-en une ci-dessus pour pouvoir publier des dessins.</div>";document.querySelectorAll("[data-delcat]").forEach(b=>b.onclick=async()=>{const cat=categories.find(c=>c.id===b.dataset.delcat);if(confirm("Supprimer cette catégorie ?")){await deleteDoc(doc(db,"categories",b.dataset.delcat));await logActivity("category-delete",cat?.name||"?");loadCategories();loadActivity();}});}
$("#categoryForm").onsubmit=async e=>{e.preventDefault();const name=$("#categoryName").value.trim();if(!name)return;await addDoc(collection(db,"categories"),{name,description:$("#categoryDesc").value.trim(),createdAt:serverTimestamp()});await logActivity("category-add",name);e.target.reset();loadCategories();loadActivity();};

$("#artForm").onsubmit=async e=>{e.preventDefault();const id=$("#artId").value;const imageUrl=$("#artImageUrl").value.trim();if(!id&&!imageUrl){alert("Ajoute l’URL de l’image.");return;}if(!$("#artCategory").value){alert("Crée d'abord une catégorie dans l'onglet Catégories, puis sélectionne-la ici.");return;}const cat=categories.find(c=>c.id===$("#artCategory").value);const steps=$("#artStepsUrls").value.split("\n").map(x=>x.trim()).filter(Boolean);const title=$("#artTitle").value.trim();const data={title,description:$("#artDescription").value.trim(),tags:$("#artTags").value.split(",").map(x=>x.trim()).filter(Boolean),categoryId:cat?.id||"",categoryName:cat?.name||"",featured:$("#artFeatured").checked,commentsEnabled:$("#artComments").checked,updatedAt:serverTimestamp()};if(imageUrl)data.imageUrl=imageUrl;if(steps.length)data.steps=steps;if(!id){data.createdAt=serverTimestamp();data.views=0;data.likesCount=0;data.authorId=auth.currentUser.uid;await addDoc(collection(db,"artworks"),data);await logActivity("artwork-add",title);}else{await updateDoc(doc(db,"artworks",id),data);await logActivity("artwork-edit",title);}e.target.reset();$("#artId").value="";loadArtworks();loadActivity();loadStats();};
$("#resetArt").onclick=()=>{$("#artForm").reset();$("#artId").value="";};
async function loadArtworks(){const s=await getDocs(query(collection(db,"artworks"),orderBy("createdAt","desc")));const list=s.docs.filter(d=>!d.data().deleted);$("#adminArtworks").innerHTML=list.map(d=>{const a=d.data();return `<div class="list-row"><span><img class="thumb" src="${a.imageUrl}"><b>${esc(a.title)}</b><small>${esc(a.categoryName||"")}</small></span><span>👁️ ${a.views||0} · ❤️ ${a.likesCount||0}</span><button class="danger-btn" data-delart="${d.id}">Supprimer</button></div>`}).join("")||"<div class='empty'>Aucun dessin pour le moment.</div>";document.querySelectorAll("[data-delart]").forEach(b=>b.onclick=async()=>{const row=list.find(d=>d.id===b.dataset.delart);const title=row?.data()?.title||"?";if(confirm("Supprimer définitivement cette création ? Elle disparaîtra du site.")){await deleteDoc(doc(db,"artworks",b.dataset.delart));await logActivity("artwork-delete",title);loadArtworks();loadActivity();loadStats();}});}

async function loadUsers(){const s=await getDocs(collection(db,"users"));$("#adminUsers").innerHTML=s.docs.map(d=>{const u=d.data();return `<div class="list-row"><span><b>${esc(u.displayName||u.email||d.id)}</b><small>${esc(u.email||"")} · ${esc(u.role||"user")}</small></span><select class="role-select" data-role="${d.id}"><option ${u.role==="user"?"selected":""}>user</option><option ${u.role==="moderator"?"selected":""}>moderator</option><option ${u.role==="admin"?"selected":""}>admin</option><option ${u.role==="owner"?"selected":""}>owner</option></select></div>`}).join("");document.querySelectorAll("[data-role]").forEach(x=>x.onchange=()=>updateDoc(doc(db,"users",x.dataset.role),{role:x.value}));}
async function loadComments(){const s=await getDocs(collectionGroup(db,"comments"));const docs=s.docs.sort((a,b)=>(b.data().createdAt?.toMillis?.()||0)-(a.data().createdAt?.toMillis?.()||0));$("#adminComments").innerHTML=docs.map(d=>`<div class="list-row"><span><b>${esc(d.data().displayName)}</b><small>${esc(d.data().text)}</small></span><button class="danger-btn" data-delcomment="${d.ref.path}">Supprimer</button></div>`).join("")||"<div class='empty'>Aucun commentaire.</div>";document.querySelectorAll("[data-delcomment]").forEach(b=>b.onclick=async()=>{if(confirm("Supprimer ce commentaire ?")){await deleteDoc(doc(db,b.dataset.delcomment));loadComments();}});}
async function loadReports(){const s=await getDocs(collection(db,"reports"));$("#adminReports").innerHTML=s.docs.map(d=>`<div class="list-row"><span><b>${esc(d.data().reason||"Signalement")}</b><small>${esc(d.data().details||"")}</small></span><button class="danger-btn" data-delreport="${d.id}">Traité</button></div>`).join("")||"<div class='empty'>Aucun signalement.</div>";}
$("#newsForm").onsubmit=async e=>{e.preventDefault();const title=$("#newsTitle").value.trim();await addDoc(collection(db,"news"),{title,text:$("#newsText").value.trim(),createdAt:serverTimestamp()});await logActivity("news-add",title);e.target.reset();loadNews();loadActivity();};
async function loadNews(){const s=await getDocs(query(collection(db,"news"),orderBy("createdAt","desc")));$("#adminNews").innerHTML=s.docs.map(d=>`<div class="list-row"><span><b>${esc(d.data().title)}</b><small>${esc(d.data().text||"")}</small></span><button class="danger-btn" data-delnews="${d.id}">Supprimer</button></div>`).join("")||"<div class='empty'>Aucune actualité.</div>";}
$("#goalForm").onsubmit=async e=>{e.preventDefault();await addDoc(collection(db,"goals"),{text:$("#goalText").value.trim(),done:false,createdAt:serverTimestamp()});e.target.reset();loadGoals();};
async function loadGoals(){const s=await getDocs(collection(db,"goals"));$("#adminGoals").innerHTML=s.docs.map(d=>`<div class="list-row"><span>${d.data().done?"☑️":"⬜"} ${esc(d.data().text)}</span><button class="ghost-btn" data-done="${d.id}">Basculer</button></div>`).join("")||"<div class='empty'>Aucun objectif.</div>";document.querySelectorAll("[data-done]").forEach(b=>b.onclick=async()=>{const d=await getDoc(doc(db,"goals",b.dataset.done));await updateDoc(doc(db,"goals",b.dataset.done),{done:!d.data().done});loadGoals();});}

// Apparence : couleur, symbole, texte d'accueil, favicon — tout est stocké en URL, pas de fichier uploadé
$("#appearanceForm").onsubmit=async e=>{e.preventDefault();const data={symbol:$("#siteSymbol").value.trim(),accent:$("#siteAccent").value,heroTitle:$("#siteHeroTitle").value.trim(),heroText:$("#siteHeroText").value.trim(),heroImage:$("#siteHeroImageUrl").value.trim(),faviconUrl:$("#siteFaviconUrl").value.trim(),animationsEnabled:$("#animationsEnabled").checked};await setDoc(doc(db,"settings","site"),data,{merge:true});alert("Apparence enregistrée.");};
$("#settingsForm").onsubmit=async e=>{e.preventDefault();await setDoc(doc(db,"settings","site"),{email:$("#siteEmail").value.trim(),instagram:$("#instagram").value.trim(),tiktok:$("#tiktok").value.trim(),youtube:$("#youtube").value.trim(),announcement:$("#siteAnnouncement").value.trim(),maintenance:$("#maintenance").checked},{merge:true});alert("Paramètres enregistrés.");};
async function loadSettings(){const s=await getDoc(doc(db,"settings","site"));if(!s.exists())return;const x=s.data();$("#siteSymbol").value=x.symbol||"";$("#siteAccent").value=x.accent||"#9b7cff";$("#siteHeroTitle").value=x.heroTitle||"";$("#siteHeroText").value=x.heroText||"";$("#siteHeroImageUrl").value=x.heroImage||"";$("#siteFaviconUrl").value=x.faviconUrl||"";$("#animationsEnabled").checked=x.animationsEnabled!==false;$("#siteEmail").value=x.email||"";$("#instagram").value=x.instagram||"";$("#tiktok").value=x.tiktok||"";$("#youtube").value=x.youtube||"";$("#siteAnnouncement").value=x.announcement||"";$("#maintenance").checked=!!x.maintenance;}
async function loadStats(){const a=await getDocs(collection(db,"artworks"));const artList=a.docs.filter(d=>!d.data().deleted);const u=await getDocs(collection(db,"users"));const c=await getDocs(collection(db,"categories"));const views=artList.reduce((n,d)=>n+(d.data().views||0),0);$("#adminStats").innerHTML=[["🎨",artList.length,"Créations"],["👥",u.size,"Utilisateurs"],["📁",c.size,"Catégories"],["👁️",views,"Vues"]].map(x=>`<div class="stat-card"><b>${x[0]}</b><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join("");}
